
package verify;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ValidateCodeWebServiceSoap", targetNamespace = "http://WebXml.com.cn/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ValidateCodeWebServiceSoap {


    /**
     * 
     * @param byString
     */
    @WebMethod(action = "http://WebXml.com.cn/smallValidateImage")
    @RequestWrapper(localName = "smallValidateImage", targetNamespace = "http://WebXml.com.cn/", className = "verify.SmallValidateImage")
    @ResponseWrapper(localName = "smallValidateImageResponse", targetNamespace = "http://WebXml.com.cn/", className = "verify.SmallValidateImageResponse")
    public void smallValidateImage(
        @WebParam(name = "byString", targetNamespace = "http://WebXml.com.cn/")
        String byString);

    /**
     * 
     * @param byString
     * @return
     *     returns byte[]
     */
    @WebMethod(action = "http://WebXml.com.cn/smallValidateByte")
    @WebResult(name = "smallValidateByteResult", targetNamespace = "http://WebXml.com.cn/")
    @RequestWrapper(localName = "smallValidateByte", targetNamespace = "http://WebXml.com.cn/", className = "verify.SmallValidateByte")
    @ResponseWrapper(localName = "smallValidateByteResponse", targetNamespace = "http://WebXml.com.cn/", className = "verify.SmallValidateByteResponse")
    public byte[] smallValidateByte(
        @WebParam(name = "byString", targetNamespace = "http://WebXml.com.cn/")
        String byString);

    /**
     * 
     * @param byString
     */
    @WebMethod(action = "http://WebXml.com.cn/enValidateImage")
    @RequestWrapper(localName = "enValidateImage", targetNamespace = "http://WebXml.com.cn/", className = "verify.EnValidateImage")
    @ResponseWrapper(localName = "enValidateImageResponse", targetNamespace = "http://WebXml.com.cn/", className = "verify.EnValidateImageResponse")
    public void enValidateImage(
        @WebParam(name = "byString", targetNamespace = "http://WebXml.com.cn/")
        String byString);

    /**
     * 
     * @param byString
     * @return
     *     returns byte[]
     */
    @WebMethod(action = "http://WebXml.com.cn/enValidateByte")
    @WebResult(name = "enValidateByteResult", targetNamespace = "http://WebXml.com.cn/")
    @RequestWrapper(localName = "enValidateByte", targetNamespace = "http://WebXml.com.cn/", className = "verify.EnValidateByte")
    @ResponseWrapper(localName = "enValidateByteResponse", targetNamespace = "http://WebXml.com.cn/", className = "verify.EnValidateByteResponse")
    public byte[] enValidateByte(
        @WebParam(name = "byString", targetNamespace = "http://WebXml.com.cn/")
        String byString);

    /**
     * 
     * @param byString
     */
    @WebMethod(action = "http://WebXml.com.cn/cnValidateImage")
    @RequestWrapper(localName = "cnValidateImage", targetNamespace = "http://WebXml.com.cn/", className = "verify.CnValidateImage")
    @ResponseWrapper(localName = "cnValidateImageResponse", targetNamespace = "http://WebXml.com.cn/", className = "verify.CnValidateImageResponse")
    public void cnValidateImage(
        @WebParam(name = "byString", targetNamespace = "http://WebXml.com.cn/")
        String byString);

    /**
     * 
     * @param byString
     * @return
     *     returns byte[]
     */
    @WebMethod(action = "http://WebXml.com.cn/cnValidateByte")
    @WebResult(name = "cnValidateByteResult", targetNamespace = "http://WebXml.com.cn/")
    @RequestWrapper(localName = "cnValidateByte", targetNamespace = "http://WebXml.com.cn/", className = "verify.CnValidateByte")
    @ResponseWrapper(localName = "cnValidateByteResponse", targetNamespace = "http://WebXml.com.cn/", className = "verify.CnValidateByteResponse")
    public byte[] cnValidateByte(
        @WebParam(name = "byString", targetNamespace = "http://WebXml.com.cn/")
        String byString);

}
