
package verify;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ValidateCodeWebService", targetNamespace = "http://WebXml.com.cn/", wsdlLocation = "file:/C:/Users/Administrator.ZX-201706171804/git/wsct/wsdl/verify.wsdl")
public class ValidateCodeWebService
    extends Service
{

    private final static URL VALIDATECODEWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException VALIDATECODEWEBSERVICE_EXCEPTION;
    private final static QName VALIDATECODEWEBSERVICE_QNAME = new QName("http://WebXml.com.cn/", "ValidateCodeWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/Administrator.ZX-201706171804/git/wsct/wsdl/verify.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        VALIDATECODEWEBSERVICE_WSDL_LOCATION = url;
        VALIDATECODEWEBSERVICE_EXCEPTION = e;
    }

    public ValidateCodeWebService() {
        super(__getWsdlLocation(), VALIDATECODEWEBSERVICE_QNAME);
    }

    public ValidateCodeWebService(WebServiceFeature... features) {
        super(__getWsdlLocation(), VALIDATECODEWEBSERVICE_QNAME, features);
    }

    public ValidateCodeWebService(URL wsdlLocation) {
        super(wsdlLocation, VALIDATECODEWEBSERVICE_QNAME);
    }

    public ValidateCodeWebService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, VALIDATECODEWEBSERVICE_QNAME, features);
    }

    public ValidateCodeWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ValidateCodeWebService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ValidateCodeWebServiceSoap
     */
    @WebEndpoint(name = "ValidateCodeWebServiceSoap")
    public ValidateCodeWebServiceSoap getValidateCodeWebServiceSoap() {
        return super.getPort(new QName("http://WebXml.com.cn/", "ValidateCodeWebServiceSoap"), ValidateCodeWebServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ValidateCodeWebServiceSoap
     */
    @WebEndpoint(name = "ValidateCodeWebServiceSoap")
    public ValidateCodeWebServiceSoap getValidateCodeWebServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://WebXml.com.cn/", "ValidateCodeWebServiceSoap"), ValidateCodeWebServiceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (VALIDATECODEWEBSERVICE_EXCEPTION!= null) {
            throw VALIDATECODEWEBSERVICE_EXCEPTION;
        }
        return VALIDATECODEWEBSERVICE_WSDL_LOCATION;
    }

}
